### ISSUE TITLE
DataError: invalid input syntax for type inet: "unknown"

### ISSUE THREAD

**Issue by brainstorm** [ialbert/biostar-central#306]
I just got this backtrace on neurostars...

```
Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
   return self.dispatch(request, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
   return handler(request, *args, **kwargs)

 File "/srv/biostar/biostar/server/views.py", line 370, in get
   self.object = self.get_object()

 File "/srv/biostar/biostar/server/views.py", line 384, in get_object
   Post.update_post_views(obj, request=self.request)

 File "/srv/biostar/biostar/apps/posts/models.py", line 353, in update_post_views
   PostView.objects.create(ip=ip, post=post, date=now)

 File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 157, in create
   return self.get_queryset().create(**kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 322, in create
   obj.save(force_insert=True, using=self.db)

 File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 545, in save
   force_update=force_update, update_fields=update_fields)

 File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 573, in save_base
   updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)

 File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 654, in _save_table
   result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

 File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 687, in _do_insert
   using=using, raw=raw)

 File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 232, in _insert
   return insert_query(self.model, objs, fields, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1514, in insert_query
   return query.get_compiler(using=using).execute_sql(return_id)

 File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
   cursor.execute(sql, params)

 File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
   return self.cursor.execute(sql, params)

 File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
   six.reraise(dj_exc_type, dj_exc_value, traceback)

 File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
   return self.cursor.execute(sql, params)

DataError: invalid input syntax for type inet: "unknown"
LINE 1: ...posts_postview" ("ip", "post_id", "date") VALUES ('unknown',...
```

Don't know if it's related but the `HTTP_REFERER` seems to point to a previous (imported) post: 

```
'HTTP_REFERER': 'http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0CCYQFjAB&url=http%3A%2F%2Fneurostars.org%2Fp%2F717%2F&ei=52h3VNuvCM3IsASL6ICYAg&usg=AFQjCNE2_GYydA55YNkUN6Gwk7hOmj99jQ&bvm=bv.80642063,d.cWc&cad=rja',
```

**Comment by ialbert** [comment]
This is  handled by the proxy server (nginx) etc that is responsible for set this correctly.
