### ISSUE TITLE
Post has no attribute usergroup

### ISSUE THREAD

**Issue by brainstorm** [ialbert/biostar-central#367]
While setting up/running Biostars3 (3.0 branch) with a `./biostar.sh delete migrate index run` according to the docs I'm getting:

```
ERROR:root:Error updating forum using default
Traceback (most recent call last):
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 233, in update_backend
    do_update(backend, index, qs, start, end, total, verbosity=self.verbosity, commit=self.commit)
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 96, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/haystack/backends/whoosh_backend.py", line 196, in update
    doc = index.full_prepare(obj)
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/haystack/indexes.py", line 212, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/Users/romanvg/dev/biostar-central/biostar3/forum/search_indexes.py", line 31, in prepare
    data['domain'] = obj.root.usergroup.domain
AttributeError: 'Post' object has no attribute 'usergroup'
```

**Comment by brainstorm** [comment]
Looking at closed issues, this seems to be #341 resurfacing. I followed the thread but cannot get Biostars3 to run from a fresh install by following the readme :-/

@Lohit13, did you run into this during your test(s)?

**Comment by ialbert** [comment]
the issue is with the indices, since those exist on our system a later bug
will not be visible immediately via regular use - errors that reoccur such
as in 341 would be good to be added to the tests.

**Comment by brainstorm** [comment]
Thanks for the fixes, now it works great! @Lohit13, are you up for writing a regression test for this? :)

**Comment by Lohit13** [comment]
@brainstorm  Considering I don't know what a regression test is, I'll surely give it a go!

**Comment by brainstorm** [comment]
Oops, sorry, @Lohit13:

https://en.wikipedia.org/wiki/Regression_testing

The idea is that every time a (recurrent) bug is found, instead of just fixing it and moving on, it pays off to write a test for it so that it doesn't reappear in future releases. Kind of bad joke follows, but I hope it serves as a way to remember what this is about:

https://twitter.com/eviltrout/status/608292681341665281
