### ISSUE TITLE
UnicodeEncodeError in New post or answer to post if user as non-ascii in their name

### ISSUE THREAD

**Issue by dahlo** [ialbert/biostar-central#388]
Hello there

I just had a user complain about getting an error when posting a question, 
```
Internal Error!
Sorry about that. 
A detailed error report has been generated and has been sent to the managers. 
If the problem persists please contact the site owners.
```
After a while i got the email with an error report:
```
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/braces/views/_access.py", line 64, in dispatch
    request, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)

  File "/home/www/sites/biostar-central/biostar/server/views.py", line 503, in post
    return super(RateLimitedNewAnswer, self).post(request, *args, **kwargs)

  File "/home/www/sites/biostar-central/biostar/apps/posts/views.py", line 271, in post
    post.save()

  File "/home/www/sites/biostar-central/biostar/apps/posts/models.py", line 315, in save
    self.parent.save()

  File "/home/www/sites/biostar-central/biostar/apps/posts/models.py", line 320, in save
    super(Post, self).save(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)

  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)

  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)

  File "/home/www/sites/biostar-central/biostar/apps/q2redmine/models.py", line 91, in question_posted
    of.write(question.author.name)

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 12: ordinal not in range(128)
```
The user does indeed have a "ä" (\xe4) in their user name. 

I also got the same error when trying to respond to the question, even though my own user only has ascii characters in its name. I reproduced the error by changing user name to include a non-ascii character and trying to post a question. 

Everywhere else it seems to work fine with non-ascii, but posting and answering a post seems to be affected.

Cheers

**Comment by ialbert** [comment]
The error comes from a module that is not part of the main Biostar distribution.

    /home/www/sites/biostar-central/biostar/apps/q2redmine/models.py

the writer of the module does not handle unicode properly.

**Comment by dahlo** [comment]
Oh, right, we have a module that creates tickets in a redmine (http://www.redmine.org/) ticket queue when a new question is asked. Sorry for not noticing that in the first place!
