### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: ImportError djcelery: cannot import name _uuid_generate_random

### ISSUE THREAD

**Issue by toogy** [ialbert/biostar-central#395]
I'm planning on setting up a biostar Q&A at school and wanted to try it out locally first

I created a pyenv and followed the exact indications in biostar's doc and this is what I get:

```
biostar-test λ pyenv virtualenv 2.7.11 biostar-test
Collecting virtualenv
  Downloading virtualenv-14.0.6-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 305kB/s 
Installing collected packages: virtualenv
Successfully installed virtualenv-14.0.6
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
New python executable in /home/toogy/.pyenv/versions/biostar-test/bin/python2.7
Also creating executable in /home/toogy/.pyenv/versions/biostar-test/bin/python
Installing setuptools, pip, wheel...done.
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in /home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages
```

```
biostar-test λ pyenv activate biostar-test 
(biostar-test) biostar-test λ pip --version
pip 8.0.2 from /home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages (python 2.7)
```

```
(biostar-test) biostar-test λ g clone git@github.com:ialbert/biostar-central.git
Cloning into 'biostar-central'...
remote: Counting objects: 22966, done.
remote: Total 22966 (delta 0), reused 0 (delta 0), pack-reused 22966
Receiving objects: 100% (22966/22966), 53.34 MiB | 11.29 MiB/s, done.
Resolving deltas: 100% (16713/16713), done.
Checking connectivity... done.
(biostar-test) biostar-test λ cd biostar-central/
(biostar-test) biostar-central:master λ ls
biostar/  biostar.sh*  conf/  docs/  import/  LICENSE.txt  live/  manage.py  README.md
```

```
(biostar-test) biostar-central:master λ pip install --upgrade -r conf/requirements/base.txt
Collecting Django<1.7,>1.6 (from -r conf/requirements/base.txt (line 1))
  Downloading Django-1.6.11-py2.py3-none-any.whl (6.7MB)
    100% |████████████████████████████████| 6.7MB 80kB/s 
Collecting Jinja2==2.7.3 (from -r conf/requirements/base.txt (line 2))
  Downloading Jinja2-2.7.3.tar.gz (378kB)
    100% |████████████████████████████████| 380kB 1.8MB/s 
Collecting Markdown==2.4.1 (from -r conf/requirements/base.txt (line 3))
  Downloading Markdown-2.4.1.tar.gz (279kB)
    100% |████████████████████████████████| 282kB 1.8MB/s 
Collecting MarkupSafe==0.23 (from -r conf/requirements/base.txt (line 4))
  Using cached MarkupSafe-0.23.tar.gz
Collecting Pygments==1.6 (from -r conf/requirements/base.txt (line 5))
  Downloading Pygments-1.6.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 307kB/s 
Collecting South==0.8.4 (from -r conf/requirements/base.txt (line 6))
  Downloading South-0.8.4-py2.py3-none-any.whl (135kB)
    100% |████████████████████████████████| 139kB 2.3MB/s 
Collecting Sphinx==1.2.2 (from -r conf/requirements/base.txt (line 7))
  Downloading Sphinx-1.2.2-py27-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 372kB/s 
Collecting Whoosh==2.6.0 (from -r conf/requirements/base.txt (line 8))
  Downloading Whoosh-2.6.0.zip (1.2MB)
    100% |████████████████████████████████| 1.2MB 387kB/s 
Collecting akismet==0.2.0 (from -r conf/requirements/base.txt (line 9))
  Downloading akismet-0.2.0.tar.gz
Collecting amqp==1.4.5 (from -r conf/requirements/base.txt (line 10))
  Downloading amqp-1.4.5-py27-none-any.whl (49kB)
    100% |████████████████████████████████| 53kB 7.9MB/s 
Collecting anyjson==0.3.3 (from -r conf/requirements/base.txt (line 11))
  Downloading anyjson-0.3.3.tar.gz
Collecting billiard==3.3.0.17 (from -r conf/requirements/base.txt (line 12))
  Downloading billiard-3.3.0.17.tar.gz (151kB)
    100% |████████████████████████████████| 151kB 2.4MB/s 
Collecting bleach==1.4 (from -r conf/requirements/base.txt (line 13))
  Downloading bleach-1.4.tar.gz
Collecting celery==3.1.12 (from -r conf/requirements/base.txt (line 14))
  Downloading celery-3.1.12-py2.py3-none-any.whl (513kB)
    100% |████████████████████████████████| 516kB 866kB/s 
Collecting chardet==2.2.1 (from -r conf/requirements/base.txt (line 15))
  Downloading chardet-2.2.1-py2.py3-none-any.whl (180kB)
    100% |████████████████████████████████| 184kB 2.3MB/s 
Collecting django-allauth==0.17.0 (from -r conf/requirements/base.txt (line 16))
  Downloading django-allauth-0.17.0.tar.gz (296kB)
    100% |████████████████████████████████| 299kB 1.3MB/s 
Collecting django-appconf==0.6 (from -r conf/requirements/base.txt (line 17))
  Downloading django-appconf-0.6.tar.gz
Collecting django-braces==1.4.0 (from -r conf/requirements/base.txt (line 18))
  Downloading django_braces-1.4.0-py2.py3-none-any.whl
Collecting django-celery==3.1.10 (from -r conf/requirements/base.txt (line 19))
  Downloading django_celery-3.1.10-py27-none-any.whl (64kB)
    100% |████████████████████████████████| 65kB 5.8MB/s 
Collecting django-celery-email==1.0.4 (from -r conf/requirements/base.txt (line 20))
  Downloading django-celery-email-1.0.4.tar.gz
Collecting django-compressor==1.4 (from -r conf/requirements/base.txt (line 21))
  Downloading django_compressor-1.4-py2.py3-none-any.whl (114kB)
    100% |████████████████████████████████| 118kB 3.4MB/s 
Collecting django-crispy-forms==1.4.0 (from -r conf/requirements/base.txt (line 22))
  Downloading django-crispy-forms-1.4.0.tar.gz (47kB)
    100% |████████████████████████████████| 49kB 7.3MB/s 
Collecting django-debug-toolbar==1.2.1 (from -r conf/requirements/base.txt (line 23))
  Downloading django_debug_toolbar-1.2.1-py2.py3-none-any.whl (208kB)
    100% |████████████████████████████████| 208kB 2.3MB/s 
Collecting django-haystack==2.1.0 (from -r conf/requirements/base.txt (line 24))
  Downloading django-haystack-2.1.0.tar.gz (821kB)
    100% |████████████████████████████████| 823kB 510kB/s 
Collecting django-recaptcha==1.0.4 (from -r conf/requirements/base.txt (line 25))
  Downloading django-recaptcha-1.0.4.tar.gz
Collecting django-reversion==1.8.1 (from -r conf/requirements/base.txt (line 26))
  Downloading django-reversion-1.8.1.tar.gz (60kB)
    100% |████████████████████████████████| 61kB 3.0MB/s 
Collecting docutils==0.11 (from -r conf/requirements/base.txt (line 27))
  Downloading docutils-0.11.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 291kB/s 
Collecting feedparser==5.1.3 (from -r conf/requirements/base.txt (line 28))
  Downloading feedparser-5.1.3.tar.bz2 (202kB)
    100% |████████████████████████████████| 204kB 1.6MB/s 
Collecting html5lib==0.999 (from -r conf/requirements/base.txt (line 29))
  Downloading html5lib-0.999.tar.gz (885kB)
    100% |████████████████████████████████| 888kB 587kB/s 
Collecting kombu==3.0.19 (from -r conf/requirements/base.txt (line 30))
  Downloading kombu-3.0.19-py2.py3-none-any.whl (207kB)
    100% |████████████████████████████████| 208kB 1.7MB/s 
Collecting langdetect==1.0.5 (from -r conf/requirements/base.txt (line 31))
  Downloading langdetect-1.0.5.zip (993kB)
    100% |████████████████████████████████| 995kB 476kB/s 
Collecting oauthlib==0.6.3 (from -r conf/requirements/base.txt (line 32))
  Downloading oauthlib-0.6.3.tar.gz (100kB)
    100% |████████████████████████████████| 102kB 4.6MB/s 
Collecting ordereddict==1.1 (from -r conf/requirements/base.txt (line 33))
  Downloading ordereddict-1.1.tar.gz
Collecting pyparsing==2.0.2 (from -r conf/requirements/base.txt (line 34))
  Downloading pyparsing-2.0.2.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 409kB/s 
Collecting python-openid==2.2.5 (from -r conf/requirements/base.txt (line 35))
  Downloading python-openid-2.2.5.tar.gz (301kB)
    100% |████████████████████████████████| 303kB 1.4MB/s 
Collecting pytz==2014.4 (from -r conf/requirements/base.txt (line 36))
  Downloading pytz-2014.4.tar.bz2 (159kB)
    100% |████████████████████████████████| 159kB 2.0MB/s 
Collecting pyzmail==1.0.3 (from -r conf/requirements/base.txt (line 37))
  Downloading pyzmail-1.0.3.tar.gz (57kB)
    100% |████████████████████████████████| 61kB 5.9MB/s 
Collecting requests==2.3.0 (from -r conf/requirements/base.txt (line 38))
  Downloading requests-2.3.0-py2.py3-none-any.whl (452kB)
    100% |████████████████████████████████| 454kB 915kB/s 
Collecting requests-oauthlib==0.4.1 (from -r conf/requirements/base.txt (line 39))
  Downloading requests_oauthlib-0.4.1-py2.py3-none-any.whl
Collecting six==1.7.2 (from -r conf/requirements/base.txt (line 40))
  Downloading six-1.7.2-py2.py3-none-any.whl
Collecting sqlparse==0.1.11 (from -r conf/requirements/base.txt (line 41))
  Downloading sqlparse-0.1.11.tar.gz (53kB)
    100% |████████████████████████████████| 57kB 4.7MB/s 
Requirement already up-to-date: wsgiref==0.1.2 in /home/toogy/.pyenv/versions/2.7.11/lib/python2.7 (from -r conf/requirements/base.txt (line 42))
Building wheels for collected packages: Jinja2, Markdown, MarkupSafe, Pygments, Whoosh, akismet, anyjson, billiard, bleach, django-allauth, django-appconf, django-celery-email, django-crispy-forms, django-haystack, django-recaptcha, django-reversion, docutils, feedparser, html5lib, langdetect, oauthlib, ordereddict, pyparsing, python-openid, pytz, pyzmail, sqlparse
  Running setup.py bdist_wheel for Jinja2 ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/b3/c0/62/8908d15b90a7de8bd15e2e6e5f5ba1398c0d9940d62a6bf8f5
  Running setup.py bdist_wheel for Markdown ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/8a/36/c6/194b1ec927203023b2f14da934539549989c98ad0cb1c5a95d
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/94/a7/79/f79a998b64c1281cb99fa9bbd33cfc9b8b5775f438218d17a7
  Running setup.py bdist_wheel for Pygments ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/f2/37/39/4c9c8a3b568955ac5f180f7f151ce058da15b8e5983ef71bae
  Running setup.py bdist_wheel for Whoosh ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/40/e9/63/1057fad5754138c869945ce0ee026a6307daba81dcaf21c874
  Running setup.py bdist_wheel for akismet ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/27/ae/30/dc7eb65a19d5bda621724543ee4bb2b27e29f6d4096bf7f817
  Running setup.py bdist_wheel for anyjson ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/3d/9e/de/9bd4afad0b092b039d7b6414f34a1350c53f0bc15fa6bf0647
  Running setup.py bdist_wheel for billiard ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/12/95/5d/1d6202769f7dea1e334235e8a368c88db2fcfd844b13bfe9d3
  Running setup.py bdist_wheel for bleach ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/c7/fa/bd/33caa195a30b485bd059cf972565e042cfa7b492c478a47355
  Running setup.py bdist_wheel for django-allauth ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/65/ff/d8/03fdbdf06556c5207430132d67db9114524731de1c462a8d66
  Running setup.py bdist_wheel for django-appconf ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/c5/97/44/a02bca424bc6186d6cdc7a05550131948be138e7dbfc164c53
  Running setup.py bdist_wheel for django-celery-email ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/5c/a3/60/797af986d781ed571eed806878fd6c0760bbc5cff9b2dac4f5
  Running setup.py bdist_wheel for django-crispy-forms ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/2c/48/36/7c2cb6aab4ab337a344347ba5f7d354736a026700838b80d1e
  Running setup.py bdist_wheel for django-haystack ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/2c/13/b6/945be8acd32c5d6252f97c3965b5d8950009eb0542adf085ea
  Running setup.py bdist_wheel for django-recaptcha ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/0b/40/db/36bfc7e089eb8263050292dd21be843138c822d00cffdebe58
  Running setup.py bdist_wheel for django-reversion ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/bd/a3/ca/739af06432fbfacf302e9ea65a99c8d10440e5e939febbb8a2
  Running setup.py bdist_wheel for docutils ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/98/c1/35/ab2a95da2a80626c423b73e923f60b387b7872854fb06b728b
  Running setup.py bdist_wheel for feedparser ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/00/7e/5b/c535566433f7780a3cbff4cc055486bcb442676dacac4b4285
  Running setup.py bdist_wheel for html5lib ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/6b/55/00/8a4b5e3e0a63e3dd40553698199d2b57223495eab6c55310e3
  Running setup.py bdist_wheel for langdetect ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/33/1b/fa/52d5c744a5694bf277852a150625aff3a8fa9aeafe2f095082
  Running setup.py bdist_wheel for oauthlib ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/32/6c/60/588d2d8dfde712950e237f371b69d1a13310d89bc19e9a13c6
  Running setup.py bdist_wheel for ordereddict ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/4e/23/88/f33a8c7c622e6f5244c408306805de7c56dd5d36cff4346fb6
  Running setup.py bdist_wheel for pyparsing ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/16/d3/87/c86874db7c028a79eb655b3ae5a5b6995ca31b4534cac289f6
  Running setup.py bdist_wheel for python-openid ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/a6/bc/dd/01dd5a43edd00c8f8660e3d51a3ef4eb685c741a7a6032e27e
  Running setup.py bdist_wheel for pytz ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/19/72/88/5910e4cbb8e13862e254680a852e18ca37ac8973649b78b3cd
  Running setup.py bdist_wheel for pyzmail ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/bc/21/cf/0ed1c13f0d829f5c7343d26c13fea7550400b266ed754d7e50
  Running setup.py bdist_wheel for sqlparse ... done
  Stored in directory: /home/toogy/.cache/pip/wheels/bf/10/ad/0e263df7674643a4b59ba0615cd52ad7013f3a0353b3f4622e
Successfully built Jinja2 Markdown MarkupSafe Pygments Whoosh akismet anyjson billiard bleach django-allauth django-appconf django-celery-email django-crispy-forms django-haystack django-recaptcha django-reversion docutils feedparser html5lib langdetect oauthlib ordereddict pyparsing python-openid pytz pyzmail sqlparse
Installing collected packages: Django, MarkupSafe, Jinja2, Markdown, Pygments, South, docutils, Sphinx, Whoosh, akismet, amqp, anyjson, billiard, six, html5lib, bleach, kombu, pytz, celery, chardet, python-openid, requests, oauthlib, requests-oauthlib, django-allauth, django-appconf, django-braces, django-celery, django-celery-email, django-compressor, django-crispy-forms, sqlparse, django-debug-toolbar, django-haystack, django-recaptcha, django-reversion, feedparser, langdetect, ordereddict, pyparsing, pyzmail
Successfully installed Django-1.6.11 Jinja2-2.7.3 Markdown-2.4.1 MarkupSafe-0.23 Pygments-1.6 South-0.8.4 Sphinx-1.2.2 Whoosh-2.6.0 akismet-0.2.0 amqp-1.4.5 anyjson-0.3.3 billiard-3.3.0.17 bleach-1.4 celery-3.1.12 chardet-2.2.1 django-allauth-0.17.0 django-appconf-0.6 django-braces-1.4.0 django-celery-3.1.10 django-celery-email-1.0.4 django-compressor-1.4 django-crispy-forms-1.4.0 django-debug-toolbar-1.2.1 django-haystack-2.1.0 django-recaptcha-1.0.4 django-reversion-1.8.1 docutils-0.11 feedparser-5.1.3 html5lib-0.999 kombu-3.0.19 langdetect-1.0.5 oauthlib-0.6.3 ordereddict-1.1 pyparsing-2.0.2 python-openid-2.2.5 pytz-2014.4 pyzmail-1.0.3 requests-2.3.0 requests-oauthlib-0.4.1 six-1.7.2 sqlparse-0.1.11
```

```
(biostar-test) biostar-central:master λ source conf/defaults.env
(biostar-test) biostar-central:master λ ./biostar.sh init import index run
*** Initializing server on localhost:8080 with biostar.settings.base
*** Running all tests
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 25, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
django.core.exceptions.ImproperlyConfigured: ImportError djcelery: cannot import name _uuid_generate_random
```

I'm stuck :(

**Comment by ialbert** [comment]
Looks like a dependency is broken:

https://github.com/celery/kombu/issues/545

I will look into adding this to the requirements, in the meantime update Kombu

**Comment by toogy** [comment]
Thanks for your reply @ialbert :smile: 

I updated kombu to `3.0.30` but now I have a second problem :

```
(biostar-test) biostar-central:master λ pip install -I kombu==3.0.30
Collecting kombu==3.0.30
  Downloading kombu-3.0.30-py2.py3-none-any.whl (241kB)
    100% |████████████████████████████████| 241kB 1.5MB/s 
Collecting amqp<2.0,>=1.4.5 (from kombu==3.0.30)
  Downloading amqp-1.4.9-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 53kB 4.5MB/s 
Collecting anyjson>=0.3.3 (from kombu==3.0.30)
Installing collected packages: amqp, anyjson, kombu
Successfully installed amqp-1.4.5 anyjson-0.3.3 kombu-3.0.30
```

```
(biostar-test) biostar-central:master λ ./biostar.sh init import index run
*** Initializing server on localhost:8080 with biostar.settings.base
*** Running all tests
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 68, in handle_noargs
    migrations = migration.Migrations(app_label)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/south/migration/base.py", line 64, in __call__
    self.instances[app_label] = super(MigrationsMetaclass, self).__call__(app_label_to_app_module(app_label), **kwds)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/south/migration/base.py", line 90, in __init__
    self.set_application(application, force_creation, verbose_creation)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/south/migration/base.py", line 154, in set_application
    module = importlib.import_module(self.migrations_module())
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/kombu/transport/django/migrations/__init__.py", line 16, in <module>
    raise ImproperlyConfigured(SOUTH_ERROR_MESSAGE)
django.core.exceptions.ImproperlyConfigured: 
For South support, customize the SOUTH_MIGRATION_MODULES setting
to point to the correct migrations module:

    SOUTH_MIGRATION_MODULES = {
        'kombu_transport_django': 'kombu.transport.django.south_migrations',
    }
```

**Comment by ialbert** [comment]
I think what is happening is that there are leftover files from the previous versions of Kombu.

First uninstall all kombus (now you seem to have two versions actually), then install the new one.

**Comment by toogy** [comment]
I did `pip uninstall kombus` before installing the `3.0.30` version.
What is the python version you recommend for biostar?

**Comment by toogy** [comment]
I tried doing everything one more time with python `2.7` and I get the same error:
```
*** Initializing server on localhost:8080 with biostar.settings.base
*** Running all tests
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 68, in handle_noargs
    migrations = migration.Migrations(app_label)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/south/migration/base.py", line 64, in __call__
    self.instances[app_label] = super(MigrationsMetaclass, self).__call__(app_label_to_app_module(app_label), **kwds)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/south/migration/base.py", line 90, in __init__
    self.set_application(application, force_creation, verbose_creation)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/south/migration/base.py", line 154, in set_application
    module = importlib.import_module(self.migrations_module())
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/toogy/.pyenv/versions/biostar-test/lib/python2.7/site-packages/kombu/transport/django/migrations/__init__.py", line 16, in <module>
    raise ImproperlyConfigured(SOUTH_ERROR_MESSAGE)
django.core.exceptions.ImproperlyConfigured: 
For South support, customize the SOUTH_MIGRATION_MODULES setting
to point to the correct migrations module:

    SOUTH_MIGRATION_MODULES = {
        'kombu_transport_django': 'kombu.transport.django.south_migrations',
    }
```

**Comment by ialbert** [comment]
Normally we want the highest version of Python 2.7 which is now 2.7.11 but seems some of the dependencies are faltering. 

These types of problems are impossible to identify until someone reports them.  Some of the benefits of using Python 2.7 should be that it is stable .... until of course it isn't. 

The responsibility here is shared equally by the kombu developers: Why on Earth are they using a function that is clearly marked with underscore and that means "DO NOT USE THIS". On the other hand since we are on the final Python 2.7 line why mess around and remove a module function from it, what exactly is being achieved there  ... very annoying.

I run Biostar with Python 2.7.10 with no problems.

**Comment by toogy** [comment]
I installed python `2.7.10` and reinstalled everything from scratch (new `git clone` etc.)

Now I get 

```
(biostar) biostar-central:master λ ./biostar.sh init import index run
*** Initializing server on localhost:8080 with biostar.settings.base
*** Running all tests
Syncing...
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 92, in handle_noargs
    syncdb.Command().execute(**options)
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 57, in handle_noargs
    cursor = connection.cursor()
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/db/backends/__init__.py", line 160, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/db/backends/__init__.py", line 132, in _cursor
    self.ensure_connection()
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/db/backends/__init__.py", line 115, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/toogy/.pyenv/versions/biostar/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 347, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
```

which is strange :disappointed:

**Comment by toogy** [comment]
I get the exact same error trying to redo everything on another machine.

This is definitely a **bug**

**Comment by ialbert** [comment]
what it means is that it cannot create the file, by default the file wants to be in. 

    live/biostar.db 

where are you putting it to? I would not jump to conclusions too quickly, especially when the problems are of the sort: "Unable to open" or "syntax error" these are errors that are way too easy to catch. Real errors are always a lot more subtle.

**Comment by toogy** [comment]
I figured it out.

My shell is fish and the `LIVE_DIR` environment variable, set to `pwd` (in a sub-shell) was not evaluated

**Comment by alevchuk** [comment]
I'm getting the same failure when doing quick start with Python 2.7.12 from https://github.com/ialbert/biostar-central/tree/production

```
ImportError djcelery: cannot import name _uuid_generate_random
```
Stack trace: https://gist.github.com/alevchuk/302aec9261d394a64be2538c75d82814


Trying to workaround by updating to kombu-4.0.0

Now I get:
```
ImportError djcelery: No module named vine.five
```
Stack trace: https://gist.github.com/alevchuk/9f648117da1b5bbc1674177add81a0ff
