### ISSUE TITLE
ImportError: No module named 'biostar.settings.base'

### ISSUE THREAD

**Issue by toogy** [ialbert/biostar-central#396]
I got my hands on a fresh version of the `4.0` branch and I'm trying to work on it.

After installing all the requirements i get this error:

```
(biostar) [toogy@stewie biostar-central]$ python -m biostar4
Traceback (most recent call last):
  File "/home/toogy/.pyenv/versions/3.5.1/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/toogy/.pyenv/versions/3.5.1/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/toogy/tmp/biostar-test/biostar-central/biostar4/__main__.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/toogy/.pyenv/versions/biostar/lib/python3.5/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/toogy/.pyenv/versions/biostar/lib/python3.5/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/home/toogy/.pyenv/versions/biostar/lib/python3.5/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/toogy/.pyenv/versions/biostar/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/toogy/.pyenv/versions/biostar/lib/python3.5/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/toogy/.pyenv/versions/3.5.1/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'biostar.settings.base'
```

**Comment by ialbert** [comment]
that is because you are running it in the same environment as biostar2. make sure to open a new shell and not apply any type of biostar specific settings in it.

that being said, I do agree that this type of hidden behavior (this is very djano specific as it triggers on the DJANGO_MODULE_SETTINGS) is not good practice.

One thing you could work on is create an .ini file reader that applies settings in a .ini file (Python has .ini readers)  to a django configuration. I suspect this got to be already written somewhere.

**Comment by toogy** [comment]
I cloned a completely new repo (my fork of the 4.0), created a new pyenv, installed the requirements like said in the 4.0's README and this is what I get:

```
(biostar) [toogy@stewie biostar-central]$ python -m biostar4
Traceback (most recent call last):
  File "/home/toogy/.pyenv/versions/3.5.1/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/toogy/.pyenv/versions/3.5.1/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/toogy/p/github/biostar-central/biostar4/__main__.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/toogy/.pyenv/versions/biostar/lib/python3.5/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/toogy/.pyenv/versions/biostar/lib/python3.5/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/home/toogy/.pyenv/versions/biostar/lib/python3.5/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/toogy/.pyenv/versions/biostar/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/toogy/.pyenv/versions/biostar/lib/python3.5/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/toogy/.pyenv/versions/3.5.1/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'biostar'
```

Thanks a lot for the support @ialbert . I really like the project and I will be able to contribute.

**Comment by ialbert** [comment]
Emails/issues and other asynchronous communications are recommended

**Comment by toogy** [comment]
All right then
