### ISSUE TITLE
biostar installation/migration error: django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'name' used in key specification without a key length")

### ISSUE THREAD

**Issue by BanzaiTokyo** [ialbert/biostar-central#402]
after running `./biostar.sh init import index run` I get the following error (it is worth to note that up to this point everything seems to be running alright):

```
 > users:0001_initial
 > users:0002_auto__del_field_user_full_score__add_field_user_activity
 > users:0003_auto__add_tag__add_field_profile_twitter_id__add_field_profile_watch_t
FATAL ERROR - The following SQL query failed: CREATE INDEX `users_tag_4da47e07` ON `users_tag` (`name`);
The error was: (1170, "BLOB/TEXT column 'name' used in key specification without a key length")
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   = DROP TABLE `users_emaillist` CASCADE; []
   - no dry run output for delete_foreign_key() due to dynamic DDL, sorry
   = ALTER TABLE `users_profile` DROP COLUMN `twitter_id` CASCADE; []
   - no dry run output for delete_foreign_key() due to dynamic DDL, sorry
   = ALTER TABLE `users_profile` DROP COLUMN `watched_tags` CASCADE; []
   = DROP TABLE `users_profile_tags` CASCADE; []

 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: users:0003_auto__add_tag__add_field_profile_twitter_id__add_field_profile_watch_t
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/south/migration/migrators.py", line 254, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/south/migration/migrators.py", line 329, in migrate_many
    result = self.migrate(migration, database)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/south/migration/migrators.py", line 85, in run_migration
    south.db.db.execute_deferred_sql()
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/south/db/generic.py", line 318, in execute_deferred_sql
    self.execute(sql)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/sergeyepifanov/Virtualenvs/BioFromPyCharm/biostars/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'name' used in key specification without a key length")
```

**Comment by ialbert** [comment]
Interesting, it seems to have to do with a limitation of MySQL of not being able to index a text field that does not have a lenght associated with it. So it is a database issue It is not clear to me if it is possible to fix via a migration since it is that migration that cannot be applied.

Probably the migration itself should be edited. Fixing it is both simple and complicated. it just needs a width to the textfield. But I don't use MySQL and wouldn't be able to test the fix.

I will mark this as MySQL not being supported.
