### ISSUE TITLE
help with gunicorn

### ISSUE THREAD

**Issue by sbagmeijer** [ialbert/biostar-central#406]
Hello,

I am trying to get biostar to run with gunicorn but I cannot get it to start I used the start script provided and changed all locations like this:
```
#!/bin/bash
set -ue

# This is required so that the default configuration file works.
source /home/ulyaoth/ulyaoth/live/deploy/ulyaoth.env

# Setting the various access logs.
ACCESS_LOG=/home/ulyaoth/ulyaoth/live/logs/gunicorn-access.log
ERROR_LOG=/home/ulyaoth/ulyaoth/live/logs/gunicorn-error.log

# The user and group the unicorn process will run as.
NUM_WORKERS=3

# Where to bind.
BIND="unix:/tmp/biostar.sock"
#BIND="localhost:8080"

# The WSGI module that starts the process.
DJANGO_WSGI_MODULE='biostar.wsgi'

# The gunicorn instance to run.
GUNICORN="/usr/local/bin/gunicorn"

# How many requests to serve.
MAX_REQUESTS=1000

# The name of the application.
NAME="ulyaoth"

echo "gunicorn starting with DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE"

exec $GUNICORN ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --max-requests $MAX_REQUESTS\
  --bind $BIND\
```

However when i try to start it I keep getting this error:
```
[deploy]$ ./gunicorn.start.sh
gunicorn starting with DJANGO_SETTINGS_MODULE=live.deploy.ulyaoth
[2016-06-17 07:57:43 +0000] [31192] [INFO] Starting gunicorn 19.6.0
[2016-06-17 07:57:43 +0000] [31192] [INFO] Listening at: unix:/tmp/biostar.sock (31192)
[2016-06-17 07:57:43 +0000] [31192] [INFO] Using worker: sync
[2016-06-17 07:57:43 +0000] [31198] [INFO] Booting worker with pid: 31198
[2016-06-17 07:57:43 +0000] [31198] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named biostar.wsgi
[2016-06-17 07:57:43 +0000] [31198] [INFO] Worker exiting (pid: 31198)
[2016-06-17 07:57:43 +0000] [31192] [INFO] Shutting down: Master
[2016-06-17 07:57:43 +0000] [31192] [INFO] Reason: Worker failed to boot.
```

Do you know by seeing this error why it cannot find the biostar.wsgi module?
I have followed all other steps to install everything with pip without errors if I run the build in test server with the "biostar.sh" command everything works fine.

**Comment by sbagmeijer** [comment]
I suddenly noticed I am standing in the wrong directory when running the script.

starting it from the directory that contains "manage.py" and everything worked fine.
