### ISSUE TITLE
Problem running sitemap.py

### ISSUE THREAD

**Issue by 8bitcat** [ialbert/biostar-central#428]
I have a problem running my sitemao.py. I think I have narrowed it down to a circular dependency. 

Running the script from my console(pythonanywhere), give me this result

Traceback (most recent call last):
  File "sitemap.py", line 10, in <module>
    from biostar.apps.posts.models import Post
  File "/home/oneoffour/biostar-central/biostar/apps/posts/models.py", line 54, in <module>
    admin.site.register(Tag, TagAdmin)
  File "/home/oneoffour/.virtualenvs/solcell/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 92, in register
    admin_class.validate(model)
  File "/home/oneoffour/.virtualenvs/solcell/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 105, in validate
    validator = cls.validator_class()
  File "/home/oneoffour/.virtualenvs/solcell/local/lib/python2.7/site-packages/django/contrib/admin/validation.py", line 20, in __init__
    models.get_apps()
  File "/home/oneoffour/.virtualenvs/solcell/local/lib/python2.7/site-packages/django/db/models/loading.py", line 139, in get_apps
    self._populate()
  File "/home/oneoffour/.virtualenvs/solcell/local/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/home/oneoffour/.virtualenvs/solcell/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/home/oneoffour/.virtualenvs/solcell/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/oneoffour/biostar-central/biostar/server/models.py", line 16, in <module>
    from biostar.apps.posts.models import Post, Subscription, ReplyToken
ImportError: cannot import name Post

I'm no python programmer but I do know the language does not allow circular dependencies.

Looking at these two lines 
 File "sitemap.py", line 10, in <module>
    from biostar.apps.posts.models import Post

  File "/home/oneoffour/biostar-central/biostar/server/models.py", line 16, in <module>
    from biostar.apps.posts.models import Post, Subscription, ReplyToken
ImportError: cannot import name Post

It seems we are fetching again. What can I do am I even right about the dependency issue?
Please give me a hint :)

Thanks for a cool platform!

**Comment by ialbert** [comment]
You are correct in your assessment though this used to work - otherwise the code would not exist.

The way Django used to work is that it auto-magically bootstrapped everything so by the time it made to that point the models were all loaded - hence the circular import was not triggered. It looks like at some point in the Django releases this auto-loading magic loading was changed and now this code raises the error.

The solution us to move that import into the function that uses it:

    generate_sitemap

I have added this fix into a different branch.

**Comment by ialbert** [comment]
Fix is in

e7c94034f8c2a91234838f920788434a535d6522

**Comment by 8bitcat** [comment]
Thanks for the fast response!

Seems you are correct about django not loading everything auto-magically.
In order to reproduce the lines above I had to add the following
sys.path.append('/home/oneoffour/biostar-central')
os.environ['DJANGO_SETTINGS_MODULE'] = 'biostar.settings.base'
Otherwise it just gave me. 
ImportError: Could not import settings 'biostar.settings.base' (Is it on sys.path? Is there an import error in the settings file?): No module named biostar.settings.base

I even tried with python -m biostar.settings.base
produced the same error. 

Now I'm curious did you try to generate a sitemap? The fix itself did solve the dependency issue. But using the fix gives me a silent crash on CMD.

**Comment by ialbert** [comment]
not being to able to load the module is unrelated to django or biostar.

that is just a standard python import issue, the modules that you use in python must be accessible via the so called python import path. There are rules of what is visible by default (for example the current directory), you can extend the PYTHONPATH variable 

adding sys.path is just a way to extend the import path

**Comment by 8bitcat** [comment]
Okay thanks! Great to learn! Do you have any info on the silent crash?

**Comment by 8bitcat** [comment]
Just so I'm not doing anything wrong im running
`python sitemap.py`
inside the commands folder

**Comment by ialbert** [comment]
This command is a django management command. It is written as such so that it shows up when you run 

`python manage.py`

The command should be run as:

`python manage.py sitemap `
