### ISSUE TITLE
cannot run with forum.settings

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#489]
hi.
Seems i cannot run with forum.settings.
Do you have any idea?
Thank you.

#python3 manage.py migrate --settings biostar.forum.settings
Secrets module not imported: No module named 'conf.run.secrets'
WARNING	2019-10-20 01:07:44,411	decorators.<module>	9	uwsgi decorators not found, tasks are synchronous	
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/thang/.local/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/thang/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "/home/thang/.local/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/thang/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/thang/.local/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/thang/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/thang/biostar-central/biostar/forum/urls.py", line 7, in <module>
    from biostar.forum import views
  File "/home/thang/biostar-central/biostar/forum/views.py", line 17, in <module>
    from . import forms, auth, tasks, util, search
  File "/home/thang/biostar-central/biostar/forum/forms.py", line 62, in <module>
    class PostLongForm(forms.Form):
  File "/home/thang/biostar-central/biostar/forum/forms.py", line 80, in PostLongForm
    content = forms.CharField(widget=PagedownWidget(template="widgets/pagedown.html"), validators=[english_only],
TypeError: __init__() got an unexpected keyword argument 'template'

**Comment by piggybit** [comment]
i fixed it temporarily by removing the template of pagedownwidget:
use this:
content = forms.CharField(widget=PagedownWidget()...
instead of this:
content = forms.CharField(widget=PagedownWidget(template="widgets/pagedown.html")

**Comment by Natay** [comment]
That is actually the correct fix since the latest version of pagedown does not have the 'template' parameter, while the pagedown version we initially started to develop with did.
