### ISSUE TITLE
Reset password - getting an error

### ISSUE THREAD

**Issue by nithilprodapt** [ialbert/biostar-central#632]
How do I configure Emailer so that I can receive/send emails?

I'm getting the below error while trying to send email to my email address to change the password:

_UnicodeError at /accounts/password/reset/
encoding with 'idna' codec failed (UnicodeError: label empty or too long)_

Thanks.

**Comment by ialbert** [comment]
This is a curious error might be a Python socket problem,

https://bugs.python.org/issue32958

it says there that:

The error can be consistently reproduced when the first substring of the url hostname is greater than 64 characters long"

is that the case for you?

**Comment by nithilprodapt** [comment]
This is where I'm getting the error. But I'm not able to identify the issue as the hostname is not greater than 64 characters.

```
INFO    2020-06-16 12:09:03,955 test_email.handle       32      settings.EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend       
INFO    2020-06-16 12:09:04,062 test_email.handle       33      sending test email from Admin User <prodaptapps@gmail.com> to ['Admin User <prodaptapps@gmail.com>']
INFO    2020-06-16 12:09:04,126 tasks.send_email        43      sending email from=Admin User <prodaptapps@gmail.com> recipient_list=['Admin User <prodaptapps@gmail.com>'] template=test_email.html
INFO    2020-06-16 12:09:04,186 sender.send     81      sending email to: Admin User <prodaptapps@gmail.com>
ERROR   2020-06-16 12:09:04,264 tasks.send_email        63      send_email error: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

**Comment by ialbert** [comment]
what gets printed if you use

    python3 -c 'import socket; print(socket.getfqdn())'

and

    python2 -c 'import socket; print(socket.getfqdn())'

**Comment by nithilprodapt** [comment]
Its printing: 
`HP..home`

**Comment by ialbert** [comment]
ok that is really weird, do you see how it has not domain name there, 

this might be a reason for the failure though I am not sure how to test for it,

can you set a domain name on your system? the error comes somewhere deep in the stack, could be even from django,

can you also change this line:

https://github.com/ialbert/biostar-central/blob/cee371ef7345d2af0b7d217393c7235e36d9a079/biostar/emailer/tasks.py#L62

from

    except Exception as exc:

to 

    except KeyError as exec:

then try to generate the same error. This is to bypass the catching the exception and will show a full traceback of  the location that the error occurs.

**Comment by nithilprodapt** [comment]
@ialbert Thanks for your help. I'm not able to set a domain name for my system as my OS - Windows 10 Home Edition is not designed to join domains and is only designed for workgroups. 

After changing the line to  `except KeyError as exec:`, this is what I'm getting:
```
INFO    2020-06-16 18:13:55,899 test_email.handle       32      settings.EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend   
INFO    2020-06-16 18:13:56,196 test_email.handle       33      sending test email from Admin User <prodaptapps@gmail.com> to ['Admin User <prodaptapps@gmail.com>']
INFO    2020-06-16 18:13:56,525 tasks.send_email        43      sending email from=Admin User <prodaptapps@gmail.com> recipient_list=['Admin User <prodaptapps@gmail.com>'] template=test_email.html
INFO    2020-06-16 18:13:56,560 sender.send     81      sending email to: Admin User <prodaptapps@gmail.com>    
Traceback (most recent call last):
 
 File "C:\Users\nithilprodapt\.conda\envs\engine\lib\encodings\idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\nithilprodapt\.conda\envs\engine\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\nithilprodapt\.conda\envs\engine\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\nithilprodapt\.conda\envs\engine\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\nithilprodapt\.conda\envs\engine\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\nithilprodapt\Desktop\Django Techforum\techforum\emailer\management\commands\test_email.py", line 36, in handle
    from_email=from_email, subject=subject)
  File "C:\Users\nithilprodapt\Desktop\Django Techforum\techforum\emailer\tasks.py", line 58, in send_email
    email.send(context=context, from_email=from_email, recipient_list=recipient_list)
  File "C:\Users\nithilprodapt\Desktop\Django Techforum\techforum\emailer\sender.py", line 93, in send
    recipient_list=recipient_list)
  File "C:\Users\nithilprodapt\Desktop\Django Techforum\techforum\emailer\sender.py", line 108, in send_html_mail
    msg.send(fail_silently=False)
  File "C:\Users\nithilprodapt\.conda\envs\engine\lib\site-packages\django\core\mail\message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\nithilprodapt\.conda\envs\engine\lib\site-packages\django\core\mail\backends\console.py", line 34, in send_messages
    self.write_message(message)
  File "C:\Users\nithilprodapt\.conda\envs\engine\lib\site-packages\django\core\mail\backends\console.py", line 17, in write_message
    msg = message.message()
  File "C:\Users\nithilprodapt\.conda\envs\engine\lib\site-packages\django\core\mail\message.py", line 257, in message
    msg['Message-ID'] = make_msgid(domain=DNS_NAME)
  File "C:\Users\nithilprodapt\.conda\envs\engine\lib\email\utils.py", line 205, in make_msgid
    msgid = '<%d.%d.%d%s@%s>' % (timeval, pid, randint, idstring, domain)
  File "C:\Users\nithilprodapt\.conda\envs\engine\lib\site-packages\django\core\mail\utils.py", line 14, in __str__
    return self.get_fqdn()
  File "C:\Users\nithilprodapt\.conda\envs\engine\lib\site-packages\django\core\mail\utils.py", line 18, in get_fqdn
    self._fqdn = punycode(socket.getfqdn())
  File "C:\Users\nithilprodapt\.conda\envs\engine\lib\site-packages\django\utils\encoding.py", line 223, in punycode
    return domain.encode('idna').decode('ascii')
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

**Comment by ialbert** [comment]
ok see how it says the label empty or too long,

I think it means that your domain name is empty, look into why that is, it is not normal that would be like that

**Comment by ialbert** [comment]
I can now reproduce the error in Python as well

```
>>> u'..'.encode('idna')
Traceback (most recent call last):
  File "/Users/ialbert/miniconda3/envs/bioinfo/lib/python3.7/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

See also:

https://bugs.python.org/issue25880

**Comment by ialbert** [comment]
It basically states that the domain name is invalid and cannot be encoded, and it is a way to catch sending emails sending from domains that are not valid. The solution is to set a correct domain name.

**Comment by nithilprodapt** [comment]
> It basically states that the domain name is invalid and cannot be encoded, and it is a way to catch sending emails sending from domains that are not valid. The solution is to set a correct domain name.

thanks @ialbert . fixed after setting a valid domain name.
