### ISSUE TITLE
spooler error

### ISSUE THREAD

**Issue by fangpingmu** [ialbert/biostar-central#880]
I am using biostar Django + uWSGI + NGINX to deploy a local biostar forum. The website is running. However, the login does not work. 

From uwsgi-error.log, I can find a lot of errors related to spooler function.

unable to find the spooler function, have you loaded it into the spooler process ?

I then changed the spooler import in site_uwsgi.ini

; import = biostar.forum.tasks
spooler-import=biostar/forum/tasks.py

When I generate a new user, I did see two tasks under spooler folder. Unfortunately, new errors appear in uwsgi-error.log.

Traceback (most recent call last):
  File "/home/www-forum/miniconda3/lib/python3.8/site-packages/uwsgidecorators.py", line 64, in manage_spool_request
    ret = f(*vars['args'], **vars['kwargs'])
  File "/home/www-forum/biostar-central/biostar/accounts/tasks.py", line 84, in create_messages
    from biostar.accounts.models import User, Message, MessageBody
  File "/home/www-forum/biostar-central/biostar/accounts/models.py", line 4, in <module>
    from taggit.managers import TaggableManager
  File "/home/www-forum/miniconda3/lib/python3.8/site-packages/taggit/managers.py", line 6, in <module>
    from django.contrib.contenttypes.fields import GenericRelation
  File "/home/www-forum/miniconda3/lib/python3.8/site-packages/django/contrib/contenttypes/fields.py", line 6, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/home/www-forum/miniconda3/lib/python3.8/site-packages/django/contrib/contenttypes/models.py", line 133, in <module>
    class ContentType(models.Model):
  File "/home/www-forum/miniconda3/lib/python3.8/site-packages/django/db/models/base.py", line 108, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/www-forum/miniconda3/lib/python3.8/site-packages/django/apps/registry.py", line 253, in get_containing_app_config
    self.check_apps_ready()
  File "/home/www-forum/miniconda3/lib/python3.8/site-packages/django/apps/registry.py", line 136, in check_apps_ready
raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

https://docs.djangoproject.com/en/3.2/ref/applications/#troubleshooting

I have tried to follow the above suggestions to call django.setup() in tasks.py, and this leads “RuntimeError: populate() isn't reentrant”. 

It seems that my python environment is problematic when spooler function tasks.py is called. How can I fix this problem?

Thanks

**Comment by fangpingmu** [comment]
resolved.
